server_endpoint = "/run/user/1000/clipcat/grpc.sock"
finder = "fzf"
preview_length = 80

[custom_finder]
program = "fzf"
args = []

[log]
emit_journald = true
emit_stdout = false
emit_stderr = false
level = "INFO"
